# Generated by Django 5.1 on 2024-08-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_membre', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cd',
        ),
        migrations.DeleteModel(
            name='Dvd',
        ),
        migrations.DeleteModel(
            name='JeuxDePlateau',
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
    ]
