# Generated by Django 5.1 on 2024-08-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='name',
            new_name='nom',
        ),
    ]
